#ifndef SIMULATION_ELEMENTARY_CELLULAR_AUTOMATON_DISPLAY_
#define SIMULATION_ELEMENTARY_CELLULAR_AUTOMATON_DISPLAY_

void OpenCVWindowInit(int w,int h);
void OpenCVWindow(std::vector<bool>& v);

#endif /*SIMULATION_ELEMENTARY_CELLULAR_AUTOMATON_DISPLAY_*/